name: tscircuit Smoke Init Test

on:
  pull_request:

jobs:
  smoke-init-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run smoke test
        run: bun run scripts/smoke-init-test.ts